# Generated by Django 5.0.3 on 2024-04-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0002_alter_about_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
