# Generated by Django 5.0.3 on 2024-04-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0003_alter_about_content_alter_about_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="video",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
