# Generated by Django 5.0.3 on 2024-04-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0004_alter_about_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="icon_content",
        ),
        migrations.RemoveField(
            model_name="about",
            name="icon_title",
        ),
        migrations.RemoveField(
            model_name="about",
            name="video",
        ),
        migrations.AlterField(
            model_name="about",
            name="content",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
