# Generated by Django 5.0.3 on 2024-04-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0005_remove_about_icon_content_remove_about_icon_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Count",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctor", models.IntegerField(default=0)),
                ("departments", models.IntegerField(default=0)),
                ("labs", models.IntegerField(default=0)),
                ("awards", models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name="About",
        ),
    ]
