# Generated by Django 5.0.3 on 2024-04-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0006_count_delete_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=128)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "male"), ("F", "female")],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "disease_id",
                    models.ManyToManyField(
                        null=True, related_name="patients", to="med.disease"
                    ),
                ),
            ],
        ),
    ]
