# Generated by Django 5.0.3 on 2024-04-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0007_disease_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=128)),
                ("job", models.CharField(max_length=128)),
                ("body", models.TextField()),
                ("icon", models.CharField(max_length=128)),
                ("icon_link", models.CharField(max_length=128)),
            ],
        ),
    ]
