# Generated by Django 5.0.3 on 2024-04-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0008_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="foto",
            field=models.ImageField(default="media/default.jpg", upload_to="media/"),
        ),
    ]
