# Generated by Django 5.0.3 on 2024-04-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0010_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="icon_link",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="icon",
        ),
        migrations.AddField(
            model_name="doctor",
            name="icon",
            field=models.ManyToManyField(
                null=True, related_name="doctors", to="med.icon"
            ),
        ),
    ]
