# Generated by Django 5.0.3 on 2024-04-04 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0011_remove_doctor_icon_link_remove_doctor_icon_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="icon",
        ),
        migrations.AddField(
            model_name="doctor",
            name="icon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor",
                to="med.icon",
            ),
        ),
    ]
