# Generated by Django 5.0.3 on 2024-04-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0012_remove_doctor_icon_doctor_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="icon",
        ),
        migrations.AddField(
            model_name="doctor",
            name="link",
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
