# Generated by Django 5.0.3 on 2024-04-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0013_remove_doctor_icon_doctor_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="disease_id",
            field=models.ManyToManyField(related_name="patients", to="med.disease"),
        ),
    ]
