# Generated by Django 5.0.3 on 2024-04-06 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0014_alter_patient_disease_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="disease_id",
        ),
        migrations.AddField(
            model_name="patient",
            name="disease_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to="med.disease",
            ),
            preserve_default=False,
        ),
    ]
