# Generated by Django 5.0.3 on 2024-04-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0015_remove_patient_disease_id_patient_disease_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("Male", "male"), ("Female", "female")],
                max_length=6,
                null=True,
            ),
        ),
    ]
