# Generated by Django 5.0.3 on 2024-04-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0016_alter_patient_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disease",
            name="description",
        ),
    ]
