# Generated by Django 5.0.3 on 2024-04-13 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0017_remove_disease_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="icon",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor",
                to="med.icon",
            ),
        ),
    ]
