# Generated by Django 5.0.3 on 2024-04-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0019_remove_doctor_icon_doctor_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="icon",
        ),
        migrations.CreateModel(
            name="PatientDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("age", models.IntegerField()),
                ("sickness", models.TextField(null=True)),
                ("appointment_date", models.DateField()),
                (
                    "doctor",
                    models.ManyToManyField(related_name="doctors", to="med.doctor"),
                ),
            ],
        ),
    ]
