# Generated by Django 5.0.3 on 2024-04-14 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0020_remove_doctor_icon_patientdoctor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientdoctor",
            name="doctor",
        ),
        migrations.AddField(
            model_name="patientdoctor",
            name="doctor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctors",
                to="med.doctor",
            ),
            preserve_default=False,
        ),
    ]
