# Generated by Django 5.0.3 on 2024-04-15 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0022_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
