# Generated by Django 5.0.3 on 2024-04-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0023_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("body", models.TextField()),
                (
                    "image",
                    models.ImageField(default="media/default.jpg", upload_to="media/"),
                ),
                ("tab", models.IntegerField(default=1)),
            ],
        ),
    ]
