 Generated by Django 5.0.3 on 2024-04-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("med", "0024_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="tab",
            field=models.IntegerField(),
        ),
    ]
